jenkins:
  systemMessage: "Jenkins Configured using Code"

  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"  

  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${adminpw:-passw0rd}

  remotingSecurity:
    enabled: true    

tool:
  git:
    installations:
      - name: Default
        home: "git"