jobs:
  - script: >
      job('Job_DSL_Seed') {
        scm {
          git {
            remote {
              url 'https://github.com/pi-unnerup/jenkins.git'
            }
          }
        }
        steps {
          jobDsl {
            targets 'dsl.groovy'
          }
        }
      }