jobs:
  - script: >
      pipelineJob('seed-dsl') {
          definition {
              triggers {
                  cron('H/5 * * * *')
              }
              cpsScm {
                  scm {
                    git {
                        remote { url 'https://github.com/pi-unnerup/jenkins.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
                  scriptPath 'Jenkinsfile'
              }
          }
      }
